Readable json + updated models examples
src-d/models pull request #20
Opened 2019-05-02 10:05 UTC by glimow

must be merged after https://github.com/src-d/models/pull/18

2019-05-02 11:19 UTC, irinakhismatullina requested changes

2019-05-02 11:19 UTC, irinakhismatullina commented on bow/1e0deee4-7dc1-400f-acb6-74c0f4aec471.md
> +import modelforge.models
```suggestion
import modelforge.backends
```

2019-05-02 11:19 UTC, irinakhismatullina commented on bow/1e0deee4-7dc1-400f-acb6-74c0f4aec471.md
> +import modelforge.models
And in all the other places

2019-05-06 16:10 UTC, glimow commented
@irinakhismatullina @vmarkovtsev PTAL

2019-05-07 15:15 UTC, vmarkovtsev requested changes

2019-05-07 15:15 UTC, vmarkovtsev commented on README.md
> +import modelforge.backends
No longer needed after https://github.com/src-d/modelforge/pull/92

2019-05-07 15:15 UTC, vmarkovtsev commented on index.json
> +{
Can you please split this PR into two:

1. Readable JSON, no other changes.
2. Extra swagger you add to JSON and generate to Markdown

2019-05-22 16:35 UTC, closed without merging